sever:
  port: 8080
spring:
  datasource:
    url: URL_TO_DATABASE
    username: username_of_data_base
    password: password_of_user
    driver-class-name: your-driver_of_datatbase
  jpa:
    show-sql: true/false
    hibernate:
      ddl-auto: create-drop
